# Generated by Django 5.1.3 on 2025-11-12 05:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('employee_id', models.CharField(db_index=True, help_text='Unique employee identifier', max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('computer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_invited', models.BooleanField(default=False, help_text='Has invitation been sent?')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, help_text='One-time password for first login', max_length=20, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_used', models.BooleanField(default=False)),
                ('reset_otp', models.CharField(blank=True, max_length=20, null=True)),
                ('reset_otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('reset_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(db_index=True, max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('total_duration', models.IntegerField(default=0, help_text='Total duration in seconds')),
                ('switch_count', models.IntegerField(default=0, help_text='Number of times switched to this app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-total_duration'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.IntegerField(choices=[(0, 'Window Change'), (1, 'Application Change'), (2, 'Input'), (3, 'Idle'), (4, 'Custom')], default=0)),
                ('window_title', models.CharField(blank=True, max_length=500, null=True)),
                ('process_name', models.CharField(db_index=True, max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracker_api.session')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='tracker_api_employe_0f53e4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='tracker_api_role_3ffc7d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationusagestats',
            index=models.Index(fields=['user', 'date'], name='tracker_api_user_id_b18754_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationusagestats',
            index=models.Index(fields=['date'], name='tracker_api_date_3eb7f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationusagestats',
            unique_together={('user', 'process_name', 'date')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', '-start_time'], name='tracker_api_user_id_909474_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='tracker_api_start_t_cdb116_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['session', '-start_time'], name='tracker_api_session_224876_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['process_name'], name='tracker_api_process_06642b_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_time'], name='tracker_api_start_t_94d56e_idx'),
        ),
    ]
