# Generated by Django 5.2.8 on 2025-11-14 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='metric_token',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous user identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='metric_token',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous user identifier', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tracker_api.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['metric_token', '-start_time'], name='tracker_api_metric__e34821_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['metric_token', '-start_time'], name='tracker_api_metric__f4d070_idx'),
        ),
    ]
