# Generated by Django 5.2.8 on 2025-11-18 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0002_activity_metric_token_session_metric_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(db_index=True, help_text='Application process name (e.g., chrome.exe)', max_length=200)),
                ('display_name', models.CharField(help_text='Human-readable name (e.g., Google Chrome)', max_length=200)),
                ('category', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('NON_PRODUCTIVE', 'Non-Productive')], default='NEUTRAL', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Why this app is categorized this way', null=True)),
                ('is_global', models.BooleanField(default=True, help_text='Applies to all departments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'App Categories',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentAppRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, help_text='Department name', max_length=100)),
                ('category_override', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('NON_PRODUCTIVE', 'Non-Productive')], help_text='Override category for this department', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why this department has different rules', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_rules', to='tracker_api.appcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dept_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Department App Rules',
                'ordering': ['department', 'app_category'],
                'unique_together': {('department', 'app_category')},
            },
        ),
        migrations.CreateModel(
            name='ManualTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('MEETING', 'Meeting'), ('PHONE_CALL', 'Phone Call'), ('FIELD_WORK', 'Field Work'), ('TRAINING', 'Training'), ('BREAK', 'Break'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Description of the activity')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration in minutes')),
                ('is_productive', models.BooleanField(default=True, help_text='Whether this activity counts as productive time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Manual Time Entries',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', '-start_time'], name='tracker_api_user_id_fdc392_idx'), models.Index(fields=['start_time'], name='tracker_api_start_t_53696e_idx')],
            },
        ),
    ]
