# Generated by Django 5.2.8 on 2025-11-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0003_appcategory_departmentapprule_manualtimeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Position description and responsibilities', null=True)),
                ('level', models.CharField(blank=True, help_text='Job level (Junior, Mid, Senior, Lead, Manager, etc.)', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this position currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Job Positions',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description and responsibilities', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this department currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_department', models.ForeignKey(blank=True, help_text='Manager/Head of this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='departmentapprule',
            name='department',
            field=models.ForeignKey(help_text='Department this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='app_rules', to='tracker_api.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text="Employee's department", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='tracker_api.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, help_text="Employee's job position", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='tracker_api.jobposition'),
        ),
    ]
