# Generated by Django 5.2.8 on 2026-02-05 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0004_jobposition_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivitySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_weight', models.FloatField(default=0.5, help_text='Default weight for uncategorized apps (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('productive_threshold', models.IntegerField(default=70, help_text="Score >= this is 'productive' (%)")),
                ('needs_improvement_threshold', models.IntegerField(default=50, help_text="Score >= this is 'needs improvement', below is 'unproductive' (%)")),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productivity Settings',
            },
        ),
        migrations.CreateModel(
            name='PositionAppWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.5, help_text='Productivity weight (0.0 = fully unproductive, 1.0 = fully productive)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reason', models.TextField(blank=True, help_text='Why this weight was assigned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_category', models.ForeignKey(help_text='Application this weight is for', on_delete=django.db.models.deletion.CASCADE, related_name='position_weights', to='tracker_api.appcategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_position_weights', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(help_text='Job position this weight applies to', on_delete=django.db.models.deletion.CASCADE, related_name='app_weights', to='tracker_api.jobposition')),
            ],
            options={
                'verbose_name_plural': 'Position App Weights',
                'ordering': ['position', 'app_category'],
                'unique_together': {('position', 'app_category')},
            },
        ),
    ]
