# Generated by Django 5.2.8 on 2026-02-12 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0005_productivitysettings_positionappweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('start_time', models.TimeField(blank=True, help_text='Shift start time (e.g. 09:00)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Shift end time (e.g. 18:00)', null=True)),
                ('is_day_off', models.BooleanField(default=False, help_text='If True, employee does not work this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Employee this shift belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='working_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Working Shift',
                'verbose_name_plural': 'Working Shifts',
                'ordering': ['user', 'day_of_week'],
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
