# Generated by Django 5.2.8 on 2026-02-12 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0006_workingshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_token', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('domain', models.CharField(db_index=True, max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('browser_process', models.CharField(db_index=True, max_length=200)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_activities', to='tracker_api.session')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['session', '-start_time'], name='tracker_api_session_41c972_idx'), models.Index(fields=['metric_token', '-start_time'], name='tracker_api_metric__7302ff_idx'), models.Index(fields=['domain'], name='tracker_api_domain_37f3fd_idx'), models.Index(fields=['start_time'], name='tracker_api_start_t_f61381_idx')],
            },
        ),
    ]
