# Generated by Django 5.2.8 on 2026-02-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0007_networkactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='lunch_break_minutes',
            field=models.IntegerField(default=60, help_text='Lunch break duration in minutes (deducted from working hours)'),
        ),
    ]
