# Generated by Django 5.2.8 on 2026-02-19 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0008_workingshift_lunch_break_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('head_of_organization', models.ForeignKey(blank=True, help_text='Head / CEO of this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_headed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this department belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='tracker_api.organization'),
        ),
    ]
