# Generated by Django 5.2.8 on 2026-02-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0009_organization_department_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('ORG_MANAGER', 'Organization Manager')], default='EMPLOYEE', max_length=20),
        ),
    ]
