# Generated by Django 5.2.8 on 2026-02-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0010_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_organization',
            field=models.ForeignKey(blank=True, help_text='Organization this user administers (only for ADMINISTRATION role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_users', to='tracker_api.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('ORG_MANAGER', 'Organization Manager'), ('ADMINISTRATION', 'Administration')], default='EMPLOYEE', max_length=20),
        ),
    ]
