# Generated by Django 5.2.8 on 2026-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_api', '0011_user_managed_organization_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('ORG_MANAGER', 'Organization Manager'), ('ORG_ADMIN', 'Organization Admin')], default='EMPLOYEE', max_length=20),
        ),
    ]
